FROM node:20

WORKDIR /app

# Copy package files
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy .env file from project root
COPY .env ./

# Copy all client files (including server.js)
COPY client/ .

# Build the app for production
RUN npm run build


# Run the server.js that's in the client folder
CMD [ "node", "app.js" ]