import pytest
import uuid
from helpers import load_mock

BASE = "/manage/organization_unit_types"
mock = load_mock("organization_unit_type")


@pytest.fixture(scope="module")
def state():
    """
    Shared state across tests in this module.
    Stores IDs created during tests so later tests can reuse them.
    """
    return {}


@pytest.fixture(scope="module")
def unique_suffix():
    """Stable random suffix for this module run."""
    return uuid.uuid4().hex[:8]


@pytest.mark.anyio
async def test_01_create_org_unit_type(api_context, auth_headers, state, unique_suffix):
    """
    POST /manage/organization_unit_types/
    Creates an organization unit type and stores its id for subsequent tests.
    """
    payload = mock["org_unit_type"].copy()

    # Make name unique to avoid conflicts with existing DB data
    payload["name"] = f"{payload['name']}-{unique_suffix}"
    payload["id"] = f"{payload['id']}-{unique_suffix}"

    r = await api_context.post(f"{BASE}/", json=payload, headers=auth_headers)
    assert r.status_code in (200, 201), r.text

    created = r.json()
    state["org_unit_type_id"] = created["id"]
    state["org_unit_type_name"] = created["name"]

    # ID should be generated by endpoint as org_unit_type|<payload.id>
    assert state["org_unit_type_id"].startswith("org_unit_type|")


@pytest.mark.anyio
async def test_02_get_all_org_unit_types(api_context, auth_headers, state):
    """
    GET /manage/organization_unit_types/
    Ensures created org unit type exists in list.
    """
    r = await api_context.get(f"{BASE}/", headers=auth_headers)
    assert r.status_code == 200, r.text

    items = r.json()
    assert any(x["id"] == state["org_unit_type_id"] for x in items)


@pytest.mark.anyio
async def test_03_get_org_unit_type_by_id(api_context, auth_headers, state):
    """
    GET /manage/organization_unit_types/{id}
    Retrieves created org unit type.
    """
    r = await api_context.get(f"{BASE}/{state['org_unit_type_id']}", headers=auth_headers)
    assert r.status_code == 200, r.text
    assert r.json()["id"] == state["org_unit_type_id"]


@pytest.mark.anyio
async def test_04_update_org_unit_type(api_context, auth_headers, state, unique_suffix):
    """
    PUT /manage/organization_unit_types/{id}
    Updates the organization unit type.
    """
    update_payload = mock["org_unit_type_update"].copy()

    r = await api_context.put(
        f"{BASE}/{state['org_unit_type_id']}",
        json=update_payload,
        headers=auth_headers
    )
    assert r.status_code == 200, r.text
    assert r.json().get("position") == update_payload["position"]


@pytest.mark.anyio
async def test_05_create_duplicate_name_returns_400(api_context, auth_headers, state):
    """
    POST /manage/organization_unit_types/ with same name should return 400
    because endpoint enforces uniqueness by name.
    """
    payload = mock["org_unit_type"].copy()

    # same name as created record -> should fail
    payload["name"] = state["org_unit_type_name"]

    # id must be different otherwise you might hit other DB constraints
    payload["id"] = f"DUP-{uuid.uuid4().hex[:6]}"

    r = await api_context.post(f"{BASE}/", json=payload, headers=auth_headers)
    assert r.status_code == 400, r.text
    assert "already exists" in (r.json().get("detail") or "").lower()


@pytest.mark.anyio
async def test_06_delete_org_unit_type(api_context, auth_headers, state):
    """
    DELETE /manage/organization_unit_types/{id}
    Deletes the created organization unit type.
    """
    r = await api_context.delete(f"{BASE}/{state['org_unit_type_id']}", headers=auth_headers)
    assert r.status_code == 200, r.text
    assert r.json()["detail"] == "Organization unit type deleted successfully"


@pytest.mark.anyio
async def test_07_get_deleted_org_unit_type_returns_404(api_context, auth_headers, state):
    """
    GET after delete should return 404.
    """
    r = await api_context.get(f"{BASE}/{state['org_unit_type_id']}", headers=auth_headers)
    assert r.status_code == 404, r.text