
SELECT 
	COUNT(t.id) as agent_number, 
	SUM(firstname) as firstname,
	SUM(surname) as surname,
	SUM(othername) as othername,
	SUM(gender) as gender,
	SUM(address) as address,
	SUM(marital_status) as marital_status,
	SUM(dependents) as dependents,
	SUM(mobile_phone) as mobile_phone,
	SUM(ref_engagement) as ref_engagement,
	SUM(ref_on_employment) as ref_on_employment,
	SUM(year_of_appointment) as year_of_appointment,
	SUM(matricule) as matricule,
	SUM(degree) as degree,
	SUM(position) as position,
	SUM(cadre) as cadre,
	SUM(classification) as classification,
	SUM(job) as job,
	SUM(salary_grade) as salary_grade,
	SUM(salaire) as salaire,
	SUM(prime) as prime,
	SUM(identifie) as identifie,
	SUM(firstname + surname + othername + gender + address) as total,
	t.facility_id as location_id
FROM (
	SELECT 
     id,
	 is_null(firstname)  AS  firstname, 
	 is_null(surname)  AS  surname, 
	 is_null(othername)  AS  othername, 
     is_null(gender)  AS  gender, 
	 is_null(address)  AS  address,
	 is_null(EXTRACT(YEAR FROM birth_date)::text)  AS  birth_date,
	 is_null(marital_status) as marital_status,
	 is_null(dependents::text) as dependents,
	 is_null(mobile_phone) as mobile_phone,
	 is_null(ref_engagement) as ref_engagement,
	 is_null(year_of_appointment::text) as year_of_appointment,
	 is_null(ref_on_employment) as ref_on_employment,
	 is_null(matricule) as matricule,
	 is_null(degree) as degree,
	 is_null(position) as position,
	 is_null(cadre) as cadre,
	 is_null(classification) as classification,
	 is_null(job) as job,
	 is_null(salary_grade) as salary_grade,
	 is_null(salaire::text) as salaire,
	 is_null(prime::text) as prime,
	 is_null(identifie::text) as identifie,
	 facility_id
     FROM z_employment_status_view
) as t
GROUP BY t.facility_id